# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCgDP3QzHH-zngG4MrUISiKfJDWPNT5Q
"""

import pandas as pd
df=pd.read_csv("/content/cleaned_stock_data.csv",parse_dates=["Date"])

df.set_index("Date",inplace=True)
df=df[['Open','High','Low','Close','Volume']]

print(df.head())
print(df.info())
print(df.describe())

#missing and duplicated
print("Missing values:\n",df.isnull().sum())
print("Duplicate rows:",df.duplicated().sum())

"""# time range and frequency
print("Start date:",df.index.min())
print("End date:",df.index.max())
print("Total records:",len(df))
print("Date frequency:",pd.infer_freq(df.index))

"""

# time range and frequency
print("Start date:",df.index.min())
print("End date:",df.index.max())
print("Total records:",len(df))
print("Date frequency:",pd.infer_freq(df.index))

# visualize the trend
import matplotlib.pyplot as plt
df['Close'].plot(figsize=(12,5),title="Close price over time")
plt.grid(True);plt.show()

# moving averages of last 20 and 50 days
df['MA20']= df['Close'].rolling(window=20).mean()
df['MA50']= df['Close'].rolling(window=50).mean()
df[['Close','MA20','MA50']].plot(figsize=(12,5),title="Close Price With Moving Averages")
plt.grid(True);
plt.show()

# daily return (means how much stock prices are changed according to the previous day)
df['Daily_Return'] = df['Close'].pct_change()
df['Daily_Return'].plot(figsize=(12,5),title="Daily Return(%) Over time",color='purple')
plt.grid(True);
plt.show()

# Daily Return distribution - visualizing  how the daily percentage changes in stock prices are spread out overtime- whether most changes are small ,big,positive,negative
import seaborn as sns
plt.figure(figsize=(10,5))
sns.histplot(df['Daily_Return'].dropna(),bins=50,color='lightblue')
sns.kdeplot(df['Daily_Return'].dropna(),color='darkblue')
plt.title("Histogram of Daily Returns")
plt.xlabel("Daily Return")
plt.grid(True)
plt.show()

#boxplot - outlier detection
sns.boxplot(x=df['Close'])
plt.title("Boxplot Of Close prices")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

Q1 = df['Close'].quantile(0.25)
Q3 = df['Close'].quantile(0.75)
IQR = Q3 - Q1

# Correct boolean mask using bitwise OR
Outliers = df[(df['Close'] < Q1 - 1.5 * IQR) | (df['Close'] > Q3 + 1.5 * IQR)]

print(f"Outliers detected: {len(Outliers)}")

plt.figure(figsize=(10, 4))
sns.boxplot(x=df['Close'])
plt.grid(True)
plt.show()

print(df['Close'].dtype)
print(df['Close'].head())

sns.heatmap(df[['Open','High','Low','Close','Volume']].corr(),annot=True,cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

print(df.head())
df.tail()

df.shape

df = df.dropna()

df.rename(columns={ "Close": "Value"}, inplace=True)
df

